# -*- coding: utf-8 -*-
"""Analyzing Naming Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gNrH-fU6Vb6--JhxOqPCU1fOoLQ3f8p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
from zipfile import ZipFile
from io import BytesIO

import pandas as pd
from zipfile import ZipFile

z = ZipFile('/content/names.zip')
a = z.namelist()

# Filter year files only
year_files = [name for name in a if name.endswith('.txt') and name.startswith('yob')]

df_list = []

for filename in year_files:
    try:
        # Extract year from file name e.g. 'yob1880.txt' → 1880
        year = int(filename[-8:-4])

        with z.open(filename) as file:
            df = pd.read_csv(file, encoding='utf-8', engine='python', header=None, names=['Name', 'Gender', 'Births'])
            df['Year'] = year  # Add year column
            df_list.append(df)
    except Exception as e:
        print(f"Error reading file {filename}: {e}")

# Combine all into one DataFrame
df = pd.concat(df_list, ignore_index=True)
display(df.head())

z = ZipFile('/content/names.zip')

a = z.namelist()

'''Then, visualize the number of male and female babies born in a particular
year with the help of pandas. DataFrame.plot, then analyze baby names
by sorting out all birth counts'''

year = 2012
data_year = df[df['Year'] == year]

sns.barplot(x='Gender', y='Births', data=data_year, estimator=sum, palette=['pink', 'lightblue'])
plt.title(f'Number of Male and Female Babies Born in {year}')
plt.show()

top_names = data_year.sort_values(by='Births', ascending=False).head(10)
print(top_names)

top_overall = df.groupby('Name')['Births'].sum().sort_values(ascending=False).head(10)
print(top_overall)

'''Then, analyze baby names by sorting out top 100 birth counts and group
them by names to find out popular baby names'''

name_group = df.groupby('Name')['Births'].sum().reset_index()
top_100 = name_group.sort_values(by='Births', ascending=False).head(100)
print(top_100)

import matplotlib.pyplot as plt
import seaborn as sns

top_10 = top_100.head(10)

plt.figure(figsize=(10,5))
sns.barplot(x='Name', y='Births', data=top_10, palette='magma')
plt.title('Top 10 Most Popular Baby Names (All Years)')
plt.xticks(rotation=45)
plt.show()

gender_group = df.groupby(['Name', 'Gender'])['Births'].sum().reset_index()
top_gender = gender_group.sort_values(by='Births', ascending=False).head(100)
print(top_gender.head(10))

sns.barplot(x='Name', y='Births', hue='Gender', data=top_gender.head(20), palette=['pink', 'lightblue'])
plt.title('Top Baby Names by Gender')
plt.xticks(rotation=45)
plt.show()

